state_sync_rpc = [
  "http://147.182.171.216:26657",
  "http://147.182.171.216:26657",
]
tendermint_flags = ["--p2p.seeds", """
    6eb3be339bb10aa256719f8f1f1304d534586b00@147.182.171.216:26656,\
"""]
btc_relayer = ["https://relayer.nomic-testnet.mappum.io:8443"]

genesis = """
{
  "app_hash": "",
  "chain_id": "nomic-testnet-7",
  "consensus_params": {
    "block": {                                                                                    "max_bytes": "22020096",
      "max_gas": "-1",
      "time_iota_ms": "1000"
    },
    "evidence": {
      "max_age_duration": "172800000000000",
      "max_age_num_blocks": "100000",
      "max_bytes": "1048576"
    },
    "validator": {
      "pub_key_types": [                                                                            "ed25519"
      ]
    },
    "version": {}
  },
  "genesis_time": "2024-11-01T23:51:18.726207997Z",                                           "initial_height": "0",
  "validators": [
    {
      "address": "5A9FCB259AB8568F4349BDD9CC6C32A145F608A0",
      "name": "",
      "power": "10",                                                                              "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "4W0VuFbYQLDpNqyiODDQboPd3qOtpSmycixYCodUIO0="
      }
    }
  ]
}
"""
