state_sync_rpc = [
    "http://147.182.171.216:26657",
    "http://147.182.171.216:26657",
]
tendermint_flags = ["--p2p.seeds", """
    dc19a04ec3145321f26f3cbe898cf4cc7fe795be@147.182.171.216:26656,\
"""]
btc_relayer = ["https://relayer.nomic-testnet.mappum.io:8443"]

genesis = """
{
  "app_hash": "",
  "chain_id": "nomic-testnet-11",
  "consensus_params": {
    "block": {
      "max_bytes": "22020096",
      "max_gas": "-1",
      "time_iota_ms": "1000"
    },
    "evidence": {
      "max_age_duration": "172800000000000",
      "max_age_num_blocks": "100000",
      "max_bytes": "1048576"
    },
    "validator": {
      "pub_key_types": [
        "ed25519"
      ]
    },
    "version": {}
  },
  "genesis_time": "2025-01-26T01:35:45.007764605Z",
  "initial_height": "0",
  "validators": [
    {
      "address": "E450BEDD3FEF4C9972A1700BD3AD066B9AB4B582",
      "name": "",
      "power": "10",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "vBnS89FyhCEz5GyW8ufyMdivGR3fh5ZG9FUeolBtvjQ="
      }
    }
  ]
}
"""
