state_sync_rpc = [
  "http://147.182.171.216:26657",
  "http://147.182.171.216:26657",
]
tendermint_flags = ["--p2p.seeds", """
    dc19a04ec3145321f26f3cbe898cf4cc7fe795be@147.182.171.216:26656,\
"""]
btc_relayer = ["https://relayer.nomic-testnet.mappum.io:8443"]

genesis = """
{
  "app_hash": "",
  "chain_id": "nomic-testnet-10",
  "consensus_params": {
    "block": {
      "max_bytes": "22020096",
      "max_gas": "-1",
      "time_iota_ms": "1000"
    },
    "evidence": {
      "max_age_duration": "172800000000000",
      "max_age_num_blocks": "100000",
      "max_bytes": "1048576"
    },
    "validator": {
      "pub_key_types": [
        "ed25519"
      ]
    },
    "version": {}
  },
  "genesis_time": "2024-12-18T17:29:53.912706232Z",
  "initial_height": "0",
  "validators": [
    {
      "address": "43226CBD07D779FF9B3DF709737E694E36941386",
      "name": "",
      "power": "10",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "FdHoLGjX6apgfx2WE5jdx9uvjtEtGbvlt+PVrq36b20="
      }
    }
  ]
}
"""
